//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SMETests.com.personifycloud.smemitst1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IMServiceSoap", Namespace="http://TIMSSSSO/imswebservice/")]
    public partial class IMService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IMSCustomerRoleGetOperationCompleted;
        
        private System.Threading.SendOrPostCallback IMSCustomerRoleGetByTimssCustomerIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback IMSRoleCustomersGetOperationCompleted;
        
        private System.Threading.SendOrPostCallback IMSVendorRolesGetOperationCompleted;
        
        private System.Threading.SendOrPostCallback IMSCustomerWebRoleGetOperationCompleted;
        
        private System.Threading.SendOrPostCallback IMSVendorWebRolesGetOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IMService() {
            this.Url = global::SMETests.Properties.Settings.Default.SMETests_com_personifycloud_smemitst1_IMService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IMSCustomerRoleGetCompletedEventHandler IMSCustomerRoleGetCompleted;
        
        /// <remarks/>
        public event IMSCustomerRoleGetByTimssCustomerIdCompletedEventHandler IMSCustomerRoleGetByTimssCustomerIdCompleted;
        
        /// <remarks/>
        public event IMSRoleCustomersGetCompletedEventHandler IMSRoleCustomersGetCompleted;
        
        /// <remarks/>
        public event IMSVendorRolesGetCompletedEventHandler IMSVendorRolesGetCompleted;
        
        /// <remarks/>
        public event IMSCustomerWebRoleGetCompletedEventHandler IMSCustomerWebRoleGetCompleted;
        
        /// <remarks/>
        public event IMSVendorWebRolesGetCompletedEventHandler IMSVendorWebRolesGetCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TIMSSSSO/imswebservice/IMSCustomerRoleGet", RequestNamespace="http://TIMSSSSO/imswebservice/", ResponseNamespace="http://TIMSSSSO/imswebservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IMSCustomerRoleGetResult IMSCustomerRoleGet(string vendorUsername, string vendorPassword, string customerToken) {
            object[] results = this.Invoke("IMSCustomerRoleGet", new object[] {
                        vendorUsername,
                        vendorPassword,
                        customerToken});
            return ((IMSCustomerRoleGetResult)(results[0]));
        }
        
        /// <remarks/>
        public void IMSCustomerRoleGetAsync(string vendorUsername, string vendorPassword, string customerToken) {
            this.IMSCustomerRoleGetAsync(vendorUsername, vendorPassword, customerToken, null);
        }
        
        /// <remarks/>
        public void IMSCustomerRoleGetAsync(string vendorUsername, string vendorPassword, string customerToken, object userState) {
            if ((this.IMSCustomerRoleGetOperationCompleted == null)) {
                this.IMSCustomerRoleGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIMSCustomerRoleGetOperationCompleted);
            }
            this.InvokeAsync("IMSCustomerRoleGet", new object[] {
                        vendorUsername,
                        vendorPassword,
                        customerToken}, this.IMSCustomerRoleGetOperationCompleted, userState);
        }
        
        private void OnIMSCustomerRoleGetOperationCompleted(object arg) {
            if ((this.IMSCustomerRoleGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IMSCustomerRoleGetCompleted(this, new IMSCustomerRoleGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TIMSSSSO/imswebservice/IMSCustomerRoleGetByTimssCustomerId", RequestNamespace="http://TIMSSSSO/imswebservice/", ResponseNamespace="http://TIMSSSSO/imswebservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IMSCustomerRoleGetResult IMSCustomerRoleGetByTimssCustomerId(string vendorUsername, string vendorPassword, string TimssCustomerId) {
            object[] results = this.Invoke("IMSCustomerRoleGetByTimssCustomerId", new object[] {
                        vendorUsername,
                        vendorPassword,
                        TimssCustomerId});
            return ((IMSCustomerRoleGetResult)(results[0]));
        }
        
        /// <remarks/>
        public void IMSCustomerRoleGetByTimssCustomerIdAsync(string vendorUsername, string vendorPassword, string TimssCustomerId) {
            this.IMSCustomerRoleGetByTimssCustomerIdAsync(vendorUsername, vendorPassword, TimssCustomerId, null);
        }
        
        /// <remarks/>
        public void IMSCustomerRoleGetByTimssCustomerIdAsync(string vendorUsername, string vendorPassword, string TimssCustomerId, object userState) {
            if ((this.IMSCustomerRoleGetByTimssCustomerIdOperationCompleted == null)) {
                this.IMSCustomerRoleGetByTimssCustomerIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIMSCustomerRoleGetByTimssCustomerIdOperationCompleted);
            }
            this.InvokeAsync("IMSCustomerRoleGetByTimssCustomerId", new object[] {
                        vendorUsername,
                        vendorPassword,
                        TimssCustomerId}, this.IMSCustomerRoleGetByTimssCustomerIdOperationCompleted, userState);
        }
        
        private void OnIMSCustomerRoleGetByTimssCustomerIdOperationCompleted(object arg) {
            if ((this.IMSCustomerRoleGetByTimssCustomerIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IMSCustomerRoleGetByTimssCustomerIdCompleted(this, new IMSCustomerRoleGetByTimssCustomerIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TIMSSSSO/imswebservice/IMSRoleCustomersGet", RequestNamespace="http://TIMSSSSO/imswebservice/", ResponseNamespace="http://TIMSSSSO/imswebservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IMSRoleCustomersGetResult IMSRoleCustomersGet(string vendorUsername, string vendorPassword, string RoleId) {
            object[] results = this.Invoke("IMSRoleCustomersGet", new object[] {
                        vendorUsername,
                        vendorPassword,
                        RoleId});
            return ((IMSRoleCustomersGetResult)(results[0]));
        }
        
        /// <remarks/>
        public void IMSRoleCustomersGetAsync(string vendorUsername, string vendorPassword, string RoleId) {
            this.IMSRoleCustomersGetAsync(vendorUsername, vendorPassword, RoleId, null);
        }
        
        /// <remarks/>
        public void IMSRoleCustomersGetAsync(string vendorUsername, string vendorPassword, string RoleId, object userState) {
            if ((this.IMSRoleCustomersGetOperationCompleted == null)) {
                this.IMSRoleCustomersGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIMSRoleCustomersGetOperationCompleted);
            }
            this.InvokeAsync("IMSRoleCustomersGet", new object[] {
                        vendorUsername,
                        vendorPassword,
                        RoleId}, this.IMSRoleCustomersGetOperationCompleted, userState);
        }
        
        private void OnIMSRoleCustomersGetOperationCompleted(object arg) {
            if ((this.IMSRoleCustomersGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IMSRoleCustomersGetCompleted(this, new IMSRoleCustomersGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TIMSSSSO/imswebservice/IMSVendorRolesGet", RequestNamespace="http://TIMSSSSO/imswebservice/", ResponseNamespace="http://TIMSSSSO/imswebservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IMSVendorRolesGetResult IMSVendorRolesGet(string vendorUsername, string vendorPassword) {
            object[] results = this.Invoke("IMSVendorRolesGet", new object[] {
                        vendorUsername,
                        vendorPassword});
            return ((IMSVendorRolesGetResult)(results[0]));
        }
        
        /// <remarks/>
        public void IMSVendorRolesGetAsync(string vendorUsername, string vendorPassword) {
            this.IMSVendorRolesGetAsync(vendorUsername, vendorPassword, null);
        }
        
        /// <remarks/>
        public void IMSVendorRolesGetAsync(string vendorUsername, string vendorPassword, object userState) {
            if ((this.IMSVendorRolesGetOperationCompleted == null)) {
                this.IMSVendorRolesGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIMSVendorRolesGetOperationCompleted);
            }
            this.InvokeAsync("IMSVendorRolesGet", new object[] {
                        vendorUsername,
                        vendorPassword}, this.IMSVendorRolesGetOperationCompleted, userState);
        }
        
        private void OnIMSVendorRolesGetOperationCompleted(object arg) {
            if ((this.IMSVendorRolesGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IMSVendorRolesGetCompleted(this, new IMSVendorRolesGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TIMSSSSO/imswebservice/IMSCustomerWebRoleGet", RequestNamespace="http://TIMSSSSO/imswebservice/", ResponseNamespace="http://TIMSSSSO/imswebservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IMSCustomerRoleGetResult IMSCustomerWebRoleGet(string vendorUsername, string vendorPassword, string customerToken) {
            object[] results = this.Invoke("IMSCustomerWebRoleGet", new object[] {
                        vendorUsername,
                        vendorPassword,
                        customerToken});
            return ((IMSCustomerRoleGetResult)(results[0]));
        }
        
        /// <remarks/>
        public void IMSCustomerWebRoleGetAsync(string vendorUsername, string vendorPassword, string customerToken) {
            this.IMSCustomerWebRoleGetAsync(vendorUsername, vendorPassword, customerToken, null);
        }
        
        /// <remarks/>
        public void IMSCustomerWebRoleGetAsync(string vendorUsername, string vendorPassword, string customerToken, object userState) {
            if ((this.IMSCustomerWebRoleGetOperationCompleted == null)) {
                this.IMSCustomerWebRoleGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIMSCustomerWebRoleGetOperationCompleted);
            }
            this.InvokeAsync("IMSCustomerWebRoleGet", new object[] {
                        vendorUsername,
                        vendorPassword,
                        customerToken}, this.IMSCustomerWebRoleGetOperationCompleted, userState);
        }
        
        private void OnIMSCustomerWebRoleGetOperationCompleted(object arg) {
            if ((this.IMSCustomerWebRoleGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IMSCustomerWebRoleGetCompleted(this, new IMSCustomerWebRoleGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://TIMSSSSO/imswebservice/IMSVendorWebRolesGet", RequestNamespace="http://TIMSSSSO/imswebservice/", ResponseNamespace="http://TIMSSSSO/imswebservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IMSVendorRolesGetResult IMSVendorWebRolesGet(string vendorUsername, string vendorPassword) {
            object[] results = this.Invoke("IMSVendorWebRolesGet", new object[] {
                        vendorUsername,
                        vendorPassword});
            return ((IMSVendorRolesGetResult)(results[0]));
        }
        
        /// <remarks/>
        public void IMSVendorWebRolesGetAsync(string vendorUsername, string vendorPassword) {
            this.IMSVendorWebRolesGetAsync(vendorUsername, vendorPassword, null);
        }
        
        /// <remarks/>
        public void IMSVendorWebRolesGetAsync(string vendorUsername, string vendorPassword, object userState) {
            if ((this.IMSVendorWebRolesGetOperationCompleted == null)) {
                this.IMSVendorWebRolesGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIMSVendorWebRolesGetOperationCompleted);
            }
            this.InvokeAsync("IMSVendorWebRolesGet", new object[] {
                        vendorUsername,
                        vendorPassword}, this.IMSVendorWebRolesGetOperationCompleted, userState);
        }
        
        private void OnIMSVendorWebRolesGetOperationCompleted(object arg) {
            if ((this.IMSVendorWebRolesGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IMSVendorWebRolesGetCompleted(this, new IMSVendorWebRolesGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TIMSSSSO/imswebservice/")]
    public partial class IMSCustomerRoleGetResult {
        
        private Role[] customerRolesField;
        
        private string[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Role[] CustomerRoles {
            get {
                return this.customerRolesField;
            }
            set {
                this.customerRolesField = value;
            }
        }
        
        /// <remarks/>
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TIMSSSSO/imswebservice/")]
    public partial class Role {
        
        private string valueField;
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TIMSSSSO/imswebservice/")]
    public partial class VendorRole {
        
        private string roleIdField;
        
        private string roleDescriptionField;
        
        private bool isActiveField;
        
        /// <remarks/>
        public string RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
            }
        }
        
        /// <remarks/>
        public string RoleDescription {
            get {
                return this.roleDescriptionField;
            }
            set {
                this.roleDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TIMSSSSO/imswebservice/")]
    public partial class IMSVendorRolesGetResult {
        
        private VendorRole[] vendorRolesField;
        
        private string[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public VendorRole[] VendorRoles {
            get {
                return this.vendorRolesField;
            }
            set {
                this.vendorRolesField = value;
            }
        }
        
        /// <remarks/>
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TIMSSSSO/imswebservice/")]
    public partial class RoleCustomer {
        
        private string roleIdField;
        
        private string timssCustomerIdField;
        
        private string searchNameField;
        
        /// <remarks/>
        public string RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
            }
        }
        
        /// <remarks/>
        public string TimssCustomerId {
            get {
                return this.timssCustomerIdField;
            }
            set {
                this.timssCustomerIdField = value;
            }
        }
        
        /// <remarks/>
        public string SearchName {
            get {
                return this.searchNameField;
            }
            set {
                this.searchNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TIMSSSSO/imswebservice/")]
    public partial class IMSRoleCustomersGetResult {
        
        private RoleCustomer[] roleCustomersField;
        
        private string[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RoleCustomer[] RoleCustomers {
            get {
                return this.roleCustomersField;
            }
            set {
                this.roleCustomersField = value;
            }
        }
        
        /// <remarks/>
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void IMSCustomerRoleGetCompletedEventHandler(object sender, IMSCustomerRoleGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IMSCustomerRoleGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IMSCustomerRoleGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IMSCustomerRoleGetResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IMSCustomerRoleGetResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void IMSCustomerRoleGetByTimssCustomerIdCompletedEventHandler(object sender, IMSCustomerRoleGetByTimssCustomerIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IMSCustomerRoleGetByTimssCustomerIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IMSCustomerRoleGetByTimssCustomerIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IMSCustomerRoleGetResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IMSCustomerRoleGetResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void IMSRoleCustomersGetCompletedEventHandler(object sender, IMSRoleCustomersGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IMSRoleCustomersGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IMSRoleCustomersGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IMSRoleCustomersGetResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IMSRoleCustomersGetResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void IMSVendorRolesGetCompletedEventHandler(object sender, IMSVendorRolesGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IMSVendorRolesGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IMSVendorRolesGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IMSVendorRolesGetResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IMSVendorRolesGetResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void IMSCustomerWebRoleGetCompletedEventHandler(object sender, IMSCustomerWebRoleGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IMSCustomerWebRoleGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IMSCustomerWebRoleGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IMSCustomerRoleGetResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IMSCustomerRoleGetResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void IMSVendorWebRolesGetCompletedEventHandler(object sender, IMSVendorWebRolesGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IMSVendorWebRolesGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IMSVendorWebRolesGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IMSVendorRolesGetResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IMSVendorRolesGetResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591